import { FormEvent, useEffect, useMemo, useState } from "react";
import { ArrowLeft, ArrowRight, Check, Eye, EyeOff, Search, ShieldCheck, Sparkles, TrendingUp } from "lucide-react";
import { toast } from "sonner";
import { startLogin } from "@/const";
import { canContinueWithInterests, filterInterests, toggleInterestSelection } from "@/lib/trendx";

type Mode = "login" | "signup" | "interests" | "platforms" | "building" | "dashboard";
type Category = "All" | "Trending" | "Education" | "Technology" | "Career" | "Lifestyle";
type Interest = { label: string; category: Exclude<Category, "All">; trending?: boolean; icon: string };

type Platform = { name: string; detail: string; status: "Available" | "Coming Soon"; icon: string; color: string };

const interests: Interest[] = [
  { label: "Artificial Intelligence", category: "Technology", trending: true, icon: "✦" }, { label: "Technology", category: "Technology", icon: "⌘" }, { label: "Competitive Exams", category: "Education", trending: true, icon: "↗" }, { label: "Startups & Business", category: "Career", trending: true, icon: "◈" }, { label: "Sports", category: "Lifestyle", trending: true, icon: "◒" }, { label: "Health & Wellness", category: "Lifestyle", trending: true, icon: "♡" }, { label: "Coding & Software", category: "Technology", icon: "</>" }, { label: "Cybersecurity", category: "Technology", icon: "◉" }, { label: "Finance & Investing", category: "Career", trending: true, icon: "₹" }, { label: "Career Development", category: "Career", icon: "↗" }, { label: "UPSC & Government Exams", category: "Education", icon: "✓" }, { label: "JEE & NEET Preparation", category: "Education", icon: "⌁" }, { label: "Science & Space", category: "Education", icon: "◎" }, { label: "News & Current Affairs", category: "Lifestyle", trending: true, icon: "◍" }, { label: "Entertainment", category: "Lifestyle", icon: "♪" }, { label: "Gaming", category: "Lifestyle", icon: "▸" }, { label: "Music", category: "Lifestyle", icon: "♫" }, { label: "Travel", category: "Lifestyle", icon: "⌖" }, { label: "Books & Learning", category: "Education", icon: "▤" }, { label: "Climate & Environment", category: "Lifestyle", trending: true, icon: "☼" }, { label: "Design & Creativity", category: "Career", icon: "✎" }, { label: "Productivity", category: "Career", icon: "✓" }, { label: "Movies & Pop Culture", category: "Lifestyle", icon: "◇" }, { label: "Entrepreneurship", category: "Career", icon: "↗" },
];

const platforms: Platform[] = [
  { name: "X", detail: "Posts, replies, reposts, hashtags and mentions", status: "Available", icon: "X", color: "#111827" },
  { name: "Telegram", detail: "Messages, channels, groups and discussions", status: "Available", icon: "T", color: "#2997d6" },
  { name: "Instagram", detail: "Public creators, posts and conversations", status: "Coming Soon", icon: "◎", color: "#d94b86" },
  { name: "Facebook", detail: "Public pages, groups and discussions", status: "Coming Soon", icon: "f", color: "#3567d6" },
  { name: "Reddit", detail: "Communities, threads and comments", status: "Coming Soon", icon: "r/", color: "#f05d32" },
  { name: "YouTube", detail: "Channels, videos and public comments", status: "Coming Soon", icon: "▶", color: "#ed3e3e" },
];

function Logo() { return <div className="simple-logo"><span>↗</span> TrendX</div>; }
function BackButton({ onClick, label = "Back" }: { onClick: () => void; label?: string }) { return <button className="back-link" onClick={onClick}><ArrowLeft size={15} /> {label}</button>; }
function profileNameFromEmail(email: string) { const local = email.split("@")[0].replace(/[._-]/g, " ").trim(); return /veenabhaganagare86/i.test(local) ? "veena" : (local.split(" ")[0] || "veena"); }

function AuthPage({ mode, setMode }: { mode: "login" | "signup"; setMode: (mode: Mode) => void }) {
  const signup = mode === "signup"; const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [confirm, setConfirm] = useState(""); const [showPassword, setShowPassword] = useState(false); const [accepted, setAccepted] = useState(false); const [error, setError] = useState("");
  const submit = (event: FormEvent) => { event.preventDefault(); setError(""); if (!email.trim() || !password.trim() || (signup && !name.trim())) return setError("Please fill in all required fields."); if (signup && password.length < 8) return setError("Password must be at least 8 characters."); if (signup && password !== confirm) return setError("Passwords do not match."); if (signup && !accepted) return setError("Please accept the terms to continue."); const displayName = signup ? name.trim().split(" ")[0] : profileNameFromEmail(email); window.localStorage.setItem("trendx-profile", displayName.toLowerCase()); toast.success(signup ? "Account created successfully." : "Signed in successfully."); setMode("interests"); };
  return <div className="simple-page"><header className="simple-header"><Logo /><span className="header-help">Your interests, made useful</span></header><main className="auth-main"><section className="simple-intro"><span className="simple-label">WELCOME TO TRENDX</span><h1>Turn your interests<br /><strong>into insights.</strong></h1><p>Choose the subjects that matter to you and get a clearer, more personal view of the ideas, trends, and opportunities worth your attention.</p><div className="intro-points"><span><ArrowRight size={14} /> Discover what is changing</span><span><ArrowRight size={14} /> Follow ideas that move you forward</span></div></section><section className="simple-card"><div className="card-heading"><h2>{signup ? "Create your TrendX profile" : "Welcome back"}</h2><p>{signup ? "Set up your interests in less than a minute." : "Sign in to continue to your personalized space."}</p></div><p className="account-switch">{signup ? "Already have an account?" : "New to TrendX?"} <button onClick={() => setMode(signup ? "login" : "signup")}>{signup ? "Sign in" : "Sign up"}</button></p><button className="google-button" onClick={() => { toast.info("Opening Google sign-in…"); startLogin(); }}><span className="google-letter">G</span> Continue with Google</button><div className="or-divider"><span>or</span></div><form onSubmit={submit}>{signup && <label>Full name<input value={name} onChange={(e) => setName(e.target.value)} placeholder="Your name" /></label>}<label>Email<input type="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="you@example.com" /></label><label>Password<span className="password-input"><input type={showPassword ? "text" : "password"} value={password} onChange={(e) => setPassword(e.target.value)} placeholder="Your password" /><button type="button" onClick={() => setShowPassword(!showPassword)} aria-label="Toggle password visibility">{showPassword ? <EyeOff size={16} /> : <Eye size={16} />}</button></span></label>{signup && <label>Confirm password<input type="password" value={confirm} onChange={(e) => setConfirm(e.target.value)} placeholder="Repeat your password" /></label>}{signup && <label className="check-row"><input type="checkbox" checked={accepted} onChange={(e) => setAccepted(e.target.checked)} /> I agree to the Terms and Privacy Policy</label>}{!signup && <button type="button" className="forgot" onClick={() => toast.info("Password recovery will be connected later.")}>Forgot password?</button>}{error && <p className="error-message">{error}</p>}<button className="primary-button" type="submit">{signup ? "Create my profile" : "Sign in"} <ArrowRight size={16} /></button></form><p className="secure-line"><ShieldCheck size={14} /> Your information is kept secure</p></section></main><footer className="simple-footer">© 2026 TrendX · Help · Privacy</footer></div>;
}

function InterestsPage({ setMode }: { setMode: (mode: Mode) => void }) { const [category, setCategory] = useState<Category>("All"); const [query, setQuery] = useState(""); const [selected, setSelected] = useState<string[]>([]); const filtered = useMemo(() => filterInterests(interests, category, query), [category, query]); const toggle = (label: string) => setSelected((current) => toggleInterestSelection(current, label)); return <div className="simple-page"><header className="simple-header"><Logo /><span className="setup-step">STEP 1 OF 3 · INTERESTS</span><BackButton onClick={() => setMode("login")} label="Back to sign in" /></header><main className="onboarding-main"><div className="onboarding-heading"><span className="simple-label">YOUR PERSONAL STARTING POINT</span><h1>Choose what you want to follow.</h1><p>Select the topics you care about. TrendX will turn them into a more relevant intelligence feed.</p></div><div className="interest-controls"><div className="category-buttons">{(["All", "Trending", "Education", "Technology", "Career", "Lifestyle"] as Category[]).map((item) => <button key={item} className={category === item ? "active" : ""} onClick={() => setCategory(item)}>{item === "Trending" && <TrendingUp size={13} />} {item}</button>)}</div><label className="search-box"><Search size={16} /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search interests" /></label></div><div className="interest-status"><p className="selected-count"><b>{selected.length}</b> selected {selected.length < 3 && "· Choose at least 3"}</p><span>Select the subjects you want to see more clearly.</span></div><div className="basic-interest-grid">{filtered.map((interest) => <button key={interest.label} className={selected.includes(interest.label) ? "selected" : ""} onClick={() => toggle(interest.label)}><span className="interest-icon">{interest.icon}</span>{interest.label}{interest.trending && <em>Trending</em>}{selected.includes(interest.label) && <Check className="interest-check" size={14} />}</button>)}</div><div className="onboarding-footer"><BackButton onClick={() => setMode("login")} /><button className="primary-button" onClick={() => { if (!canContinueWithInterests(selected)) return toast.error("Please select at least three interests."); window.localStorage.setItem("trendx-interests", JSON.stringify(selected)); setMode("platforms"); }}>Continue to platforms <ArrowRight size={16} /></button></div></main></div>; }

function PlatformsPage({ setMode }: { setMode: (mode: Mode) => void }) { const [selected, setSelected] = useState<string[]>(["X", "Telegram"]); const toggle = (name: string, status: Platform["status"]) => { if (status === "Coming Soon") return toast.info(`${name} monitoring is coming soon.`); setSelected((current) => toggleInterestSelection(current, name)); }; return <div className="simple-page"><header className="simple-header"><Logo /><span className="setup-step">STEP 2 OF 3 · PLATFORMS</span><BackButton onClick={() => setMode("interests")} label="Back to interests" /></header><main className="onboarding-main platform-main"><div className="onboarding-heading"><span className="simple-label">CHOOSE YOUR SOURCES</span><h1>Which platforms should we monitor?</h1><p>Choose the platforms you want to include in your intelligence feed. You can change these anytime.</p></div><div className="platform-list">{platforms.map((platform) => <button key={platform.name} className={`platform-row ${selected.includes(platform.name) ? "selected" : ""} ${platform.status === "Coming Soon" ? "disabled" : ""}`} onClick={() => toggle(platform.name, platform.status)}><span className="platform-icon" style={{ color: platform.color }}>{platform.icon}</span><span className="platform-info"><b>{platform.name}</b><small>{platform.detail}</small></span><span className={`platform-status ${platform.status === "Available" ? "available" : "soon"}`}>{selected.includes(platform.name) ? <Check size={13} /> : platform.status}</span></button>)}</div><div className="onboarding-footer"><BackButton onClick={() => setMode("interests")} /><button className="primary-button" onClick={() => { if (!selected.length) return toast.error("Choose at least one available platform."); window.localStorage.setItem("trendx-platforms", JSON.stringify(selected)); setMode("building"); }}>Build my intelligence feed <Sparkles size={16} /></button></div></main></div>; }

function BuildingPage({ setMode }: { setMode: (mode: Mode) => void }) { const [ready, setReady] = useState(false); useEffect(() => { const timer = window.setTimeout(() => setReady(true), 1600); return () => window.clearTimeout(timer); }, []); return <div className="simple-page"><header className="simple-header"><Logo /><span className="setup-step">STEP 3 OF 3 · BUILDING</span><BackButton onClick={() => setMode("platforms")} label="Back to platforms" /></header><main className="building-main"><div className={`building-orbit ${ready ? "ready" : ""}`}><Sparkles size={25} /></div><span className="simple-label">TRENDX ENGINE</span><h1>{ready ? "Your intelligence feed is ready." : "Building your intelligence feed."}</h1><p>{ready ? "Your selected interests and platforms are now prepared for a focused feed." : "Connecting your interests to the conversations happening across your selected platforms."}</p><div className="build-progress"><span style={{ width: ready ? "100%" : "62%" }} /></div><div className="build-steps"><span className={ready ? "done" : "active"}><Check size={13} /> Reading your interests</span><span className={ready ? "done" : "active"}><Check size={13} /> Preparing platform signals</span><span className={ready ? "done" : ""}><Check size={13} /> Shaping your feed</span></div>{ready ? <button className="primary-button open-feed-button" onClick={() => setMode("dashboard")}>Open my feed <ArrowRight size={16} /></button> : <div className="building-note">This only takes a moment…</div>}</main></div>; }

function Dashboard({ setMode }: { setMode: (mode: Mode) => void }) { const name = window.localStorage.getItem("trendx-profile") || "veena"; const selected = (() => { try { return JSON.parse(window.localStorage.getItem("trendx-interests") || "[]") as string[]; } catch { return []; } })(); const topics = selected.length ? selected : ["Technology", "Sports", "News"]; return <div className="simple-page"><header className="simple-header"><Logo /><div className="profile-chip"><span>{name.charAt(0).toUpperCase()}</span><b>{name}</b></div><button className="skip-link" onClick={() => setMode("interests")}>Edit interests</button></header><main className="dashboard-simple"><span className="simple-label">YOUR PERSONAL TRENDX</span><h1>Good morning, {name}.</h1><p className="dashboard-subtitle">Here are a few signals shaped around what you care about.</p><div className="topic-row">{topics.map((topic) => <span key={topic}>{topic}</span>)}</div><section className="basic-feed"><article><span><TrendingUp size={13} /> RISING NOW</span><h2>What is gaining attention in your world?</h2><p>Explore new ideas, conversations, and opportunities connected to your interests.</p><button onClick={() => toast.info("Your live insights feed will be connected next.")}>Explore insights <ArrowRight size={15} /></button></article><article><span><Sparkles size={13} /> YOUR SIGNAL</span><h2>Keep your feed relevant</h2><p>Refine your interests anytime so TrendX can keep improving what it brings to you.</p><button onClick={() => setMode("interests")}>Update interests <ArrowRight size={15} /></button></article></section></main></div>; }

export default function Home() { const [mode, setMode] = useState<Mode>("login"); if (mode === "interests") return <InterestsPage setMode={setMode} />; if (mode === "platforms") return <PlatformsPage setMode={setMode} />; if (mode === "building") return <BuildingPage setMode={setMode} />; if (mode === "dashboard") return <Dashboard setMode={setMode} />; return <AuthPage mode={mode} setMode={setMode} />; }
